version: '3.8'

services:
  bigquery-service:
    build: .
    container_name: gps-bigquery-service
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./tmp:/app/tmp
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis local (opcional - solo si no usas el Redis externo)
  redis:
    image: redis:7-alpine
    container_name: gps-redis
    network_mode: host
    command: redis-server --requirepass ${REDIS_PASSWORD:-mypassword}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - local-redis

volumes:
  redis_data: